{
 "title": "InfluxDB Enterprise",
 "description": "A dashboard to visualise statistics about an InfluxDB Enterprise 1.x Cluster",
 "tags": [
  "influxdb",
  "enterprise",
  "system",
  "monitoring",
  "database",
  "cluster",
  "health"
 ],
 "time": { "from": "2023-05-01T10:11:47.989Z", "to": "2023-05-01T11:57:27.921Z" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "telegraf" }
  ]
 },
 "panels": [
  { "title": "License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "License Expiry",
   "type": "table",
   "description": "Instructions on applying an updated license can be located at https://docs.influxdata.com/enterprise_influxdb/v1.10/administration/renew-license/",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"strings\"\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_entitlements\")\n    |> schema.fieldsAsCols()\n    |> filter(fn: (r) => exists r[\"host\"] and exists r[\"licenseType\"] and exists r[\"licenseExpiry\"])\n    |> group(columns: [\"_measurement\", \"cluster_id\", \"host\"])\n    |> first(column: \"url\")\n    |> map(fn: (r) => ({r with expires: strings.replaceAll(v: r.licenseExpiry, t: \"T00:00:00Z\", u: \"\")}))\n    |> keep(columns: [\"expires\", \"host\", \"node\"])\n    |> group()"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "# of Data Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"influxdb\")\n  |> filter(fn: (r) => r._field == \"n_shards\")\n  |> keyValues(keyColumns: [\"host\"])\n  |> group()\n  |> keep(columns: [\"_value\"])\n  |> count()"
    }
   ]
  },
  {
   "title": "RAM per Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\" or r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> last()\n  |> group()\n  |> max()\n  |> map(fn: (r) => ({ \n    _field: \"RAM per node\",\n    _value: r._value }))"
    }
   ]
  },
  {
   "title": "# CPU/node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\n  |> last()\n  |> group()\n  |> max()\n  |> map(fn: (r) => ({\n    _field: \"# CPU/node\",\n    _value: r._value\n  }))\n"
    }
   ]
  },
  {
   "title": "Storage Allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> filter(fn: (r) => r[\"fstype\"] != \"tmpfs\" and r[\"fstype\"] != \"devtmpfs\")\n  |> filter(fn: (r) => r[\"path\"] !~ /boot/)\n  |> last()\n  |> group()\n  |> sum()\n  |> map(fn: (r) => ({\n   _field: \"Disk allocated\",\n   _value: r._value}))\n"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> filter(fn: (r) => r[\"fstype\"] != \"tmpfs\" and r[\"fstype\"] != \"devtmpfs\")\n  |> filter(fn: (r) => r[\"path\"] !~ /boot/)\n  |> last()\n  |> group()\n  |> sum()\n  |> map(fn: (r) => ({\n  _field: \"Disk Used\",\n  _value: r._value }))\n"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "al = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> filter(fn: (r) => r[\"fstype\"] != \"tmpfs\" and r[\"fstype\"] != \"devtmpfs\")\n  |> filter(fn: (r) => r[\"path\"] !~ /boot/)\n  |> last()\n  |> group()\n  |> sum()\n  |> map(fn: (r) => ({\n    _time: 1,\n   _field: \"Disk allocated\",\n   _value: float(v: r._value) }))\n\nused = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> filter(fn: (r) => r[\"fstype\"] != \"tmpfs\" and r[\"fstype\"] != \"devtmpfs\")\n  |> filter(fn: (r) => r[\"path\"] !~ /boot/)\n  |> last()\n  |> group()\n  |> sum()\n  |> map(fn: (r) => ({\n  _time: 1,\n  _field: \"Disk Used\",\n  _value: float(v: r._value) }))\n\njoin(tables: {t1: used, t2: al}, on: [\"_time\"])\n  |> map(fn: (r) => ({\n     _value: (r._value_t1 / r._value_t2) * 100.0\n  }))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"usage_user\")\n  |> filter(fn: (r) => r[\"cpu\"] == \"cpu-total\")\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"host\", \"node\"])"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\n  |> filter(fn: (r) => r[\"_field\"] == \"load5\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"max\")"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Series Cardinality",
   "type": "timeseries",
   "description": "A per database and data-node measure of series cardinality.\n\nInformation on troubleshooting cardinality issues can be found at https://www.influxdata.com/blog/solving-runaway-series-cardinality-when-using-influxdb/ ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_database\")\n  |> filter(fn: (r) => r[\"_field\"] == \"numSeries\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"database\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "# of Shards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb\")\n  |> filter(fn: (r) => r[\"_field\"] == \"n_shards\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Hinted Handoff Queue Size",
   "type": "timeseries",
   "description": "The size of the Hinted Handoff queue.\n\nSee https://docs.influxdata.com/enterprise_influxdb/v1.10/concepts/clustering/#hinted-handoff for more information on this queue and its meaning",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_hh_processor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queueBytes\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Shard Write Errors",
   "type": "timeseries",
   "description": "Average number of shard write errors per time period.\n\nDepending on the consistency setting used, the cluster may report shard write errors when Hinted Handoff queues are not empty.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_shard\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writePointsErr\")\n  |> filter(fn: (r) => r[\"database\"] == \"_internal\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Hinted Handoff Per Destination Node ID",
   "type": "timeseries",
   "description": "Size of the Hinted Handoff queue per node, with destination node ID included.\n\nThe node ID can be matched to the output of \"influxd-ctl show\" in order to identify which node the data in the queue is (trying) to be sent to",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_hh_processor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queueBytes\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"node\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Per Host Point Throughput",
   "type": "timeseries",
   "description": "The average rate at which each node is receiving points via API. This does not include internal replication",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pointReq\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Cluster Point Throughput",
   "type": "timeseries",
   "description": "The average rate at which points are being written into the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pointReq\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> group()\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  },
  { "title": "Rates and Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Query Durations",
   "type": "timeseries",
   "description": "Average query execution duration, by time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_queryExecutor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queryDurationNs\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "description": "Average number of queries per second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_queryExecutor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queriesExecuted\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "HTTP Request Duration (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_httpd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queryReq\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(\n        every: v.windowPeriod,\n        fn: (tables=<-, column) => tables\n            |> quantile(q: 0.99, method: \"exact_selector\"),\n    )\n"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_httpd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queryReq\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\",\"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Continuous Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "q/s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_cq\")\n  |> filter(fn: (r) => r[\"_field\"] == \"queryOk\" or r[\"_field\"] == \"queryFail\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Write Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"internal_write\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_time_ns\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Write Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_httpd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writeReq\" )\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"instance\"])\n  |> difference(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Average Write Batch Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_httpd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writeReq\" or r[\"_field\"] == \"writeReqBytes\")\n  |> difference(nonNegative: true)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with _value: r.writeReqBytes / r.writeReq  \n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> keep(columns: [\"_time\", \"host\", \"_value\"])\n  "
    }
   ]
  },
  {
   "title": "Average Write Batch Size (points)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"influxdb_httpd\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pointsWrittenOK\" or r[\"_field\"] == \"pointsWrittenFail\" or r[\"_field\"] == \"pointsWrittenDropped\" or r[\"_field\"] == \"writeReq\")\n  |> difference(nonNegative: true)\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with _value: (r.pointsWrittenOK + r.pointsWrittenFail + r.pointsWrittenDropped)  / r.writeReq  \n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> keep(columns: [\"_time\", \"host\", \"_value\"])\n  "
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Disk Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"path\"])\n  \n\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Root Volume Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"disk\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_percent\")\n  |> filter(fn: (r) => r[\"mode\"] == \"rw\")\n  |> filter(fn: (r) => r[\"path\"] == \"/\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"path\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reads\" or r[\"_field\"] == \"writes\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"name\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  \n  \n"
    }
   ]
  },
  {
   "title": "I/O Queue Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"io_time\")\n  |> aggregateWindow(every: 1s, fn: last)\n  |> derivative(unit: 1ms, nonNegative: true)\n  |> group(columns: [\"time\", \"host\"], mode:\"by\")\n\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\n  |> keep(columns: [\"_time\", \"_value\", \"host\"])"
    }
   ]
  },
  {
   "title": "IOPS (Writes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"writes\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"name\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "IOPS (Reads)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reads\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"name\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk Write Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"write_bytes\")\n  |> filter(fn: (r) => r[\"name\"] != \"loop\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"name\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"diskio\")\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\")\n  |> filter(fn: (r) => r[\"name\"] != \"loop\")\n  |> keep(columns: [\"_time\", \"_field\", \"_value\", \"host\", \"name\"])\n  |> sort(columns: [\"_time\"])\n  |> derivative(unit: 1s, nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}